### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by mouzzampk2014** [XanderStrike/goplaxt#33]
Hi, could you please create a docker compose example so I can use with my existing setup. Thank you so much

**Comment by nemchik** [comment]
```yaml
  plaxt:
    container_name: plaxt
    environment:
    - TRAKT_ID=
    - TRAKT_SECRET=
    - ALLOWED_HOSTNAMES=
    - TZ=${TZ}
    image: xanderstrike/goplaxt
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
    - 8000:8000
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/plaxt:/app/keystore
    - ${DOCKERSHAREDDIR}:/shared
```

`ALLOWED_HOSTNAMES` is intentionally blank.

I may keep this open and add it to DS.
